"""Generate golden cross-language preprocessing-parity fixtures.

This is the *producer* side of the project's #1 correctness gate. It runs the
real Python preprocessing pipeline (:func:`src.dataset.get_eval_transforms`) and
the exported ONNX model over a small, fixed set of real ASL images, then writes
the reference predictions to ``web/test-fixtures/golden/``. The browser
onnxruntime-web path must reproduce these exactly (predicted class) and within a
tight tolerance (probabilities), enforced by the web parity test.

Re-run this after ANY change to preprocessing, the model, or the ONNX export::

    python -m src.gen_parity_fixtures

The fixtures are deterministic: the first image (sorted) of each chosen class is
copied verbatim into the fixtures directory so the JS side reads identical bytes.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import onnxruntime as ort
import torch
from PIL import Image

from src.dataset import (
    IMAGE_SIZE,
    IMAGENET_MEAN,
    IMAGENET_STD,
    get_class_names,
    get_eval_transforms,
)

# Visually distinct hand shapes spanning easy and harder (C, Y) cases, so the
# parity gate exercises a spread of the probability simplex rather than only
# near-one-hot outputs.
FIXTURE_CLASSES = ["A", "B", "C", "L", "W", "Y"]

DEFAULT_DATA_DIR = "data/asl_real"
DEFAULT_ONNX = "artifacts/model.onnx"
DEFAULT_OUT_DIR = "web/test-fixtures/golden"


def generate(
    data_dir: str = DEFAULT_DATA_DIR,
    onnx_path: str = DEFAULT_ONNX,
    out_dir: str = DEFAULT_OUT_DIR,
) -> dict:
    """Produce golden fixtures and write ``manifest.json`` + image copies.

    Args:
        data_dir: Root of the class-folder dataset to draw fixture images from.
        onnx_path: Path to the exported ONNX model (must match the checkpoint).
        out_dir: Destination directory for the fixture images and manifest.

    Returns:
        The manifest dict that was written to disk.

    Raises:
        FileNotFoundError: If a chosen class folder has no images.
    """
    class_names = get_class_names(data_dir)
    transform = get_eval_transforms()
    session = ort.InferenceSession(onnx_path)
    input_name = session.get_inputs()[0].name

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    fixtures = []
    for cls in FIXTURE_CLASSES:
        images = sorted((Path(data_dir) / cls).glob("*.png"))
        if not images:
            raise FileNotFoundError(f"No images for class '{cls}' under {data_dir}")
        image = Image.open(images[0]).convert("RGB")
        # Copy the exact bytes so the JS path reads an identical image (used by
        # the end-to-end parity test, which includes the browser resize).
        image.save(out_path / f"{cls}.png", format="PNG")

        # Also emit the EXACT pixels Python's Resize produced, as a 128x128 RGB
        # PNG (PNG is lossless, so a 1:1 canvas draw recovers identical bytes).
        # This lets the strict tensor-parity test remove the resampling kernel
        # from the equation and isolate the normalize/layout/model arithmetic.
        resized = image.resize((IMAGE_SIZE, IMAGE_SIZE), Image.Resampling.BILINEAR)
        resized.save(out_path / f"{cls}_resized.png", format="PNG")

        tensor = transform(image).unsqueeze(0).numpy().astype(np.float32)
        logits = session.run(None, {input_name: tensor})[0][0]
        probs = torch.softmax(torch.tensor(logits), 0).numpy()
        fixtures.append(
            {
                "file": f"{cls}.png",
                "true_class": cls,
                "pred_class": class_names[int(probs.argmax())],
                "pred_index": int(probs.argmax()),
                "probs": [round(float(x), 6) for x in probs],
                "tensor_mean": round(float(tensor.mean()), 6),
                "tensor_std": round(float(tensor.std()), 6),
                "tensor_shape": list(tensor.shape),
            }
        )

    manifest = {
        "description": (
            "Golden cross-language parity fixtures. Generated by the Python+ONNX "
            "path; the browser onnxruntime-web path MUST reproduce pred_class "
            "exactly and probs within atol=1e-3."
        ),
        "generator": "python -m src.gen_parity_fixtures",
        "image_size": IMAGE_SIZE,
        "imagenet_mean": IMAGENET_MEAN,
        "imagenet_std": IMAGENET_STD,
        "class_names": class_names,
        "onnx_input_name": input_name,
        "onnx_model": onnx_path,
        "fixtures": fixtures,
    }
    with open(out_path / "manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
    return manifest


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Generate parity fixtures.")
    parser.add_argument("--data_dir", default=DEFAULT_DATA_DIR)
    parser.add_argument("--onnx", default=DEFAULT_ONNX)
    parser.add_argument("--out_dir", default=DEFAULT_OUT_DIR)
    args = parser.parse_args()
    manifest = generate(args.data_dir, args.onnx, args.out_dir)
    print(f"Wrote {len(manifest['fixtures'])} fixtures to {args.out_dir}/")
    for fx in manifest["fixtures"]:
        conf = max(fx["probs"])
        print(f"  {fx['true_class']} -> {fx['pred_class']} ({conf:.3f})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
